import { NETWORK_TYPE } from 'constants/index';
import {
  TOKEN_CONTRACT as AELF_TOKEN_CONTRACT,
  ETRANSFER_CONTRACT as AELF_ETRANSFER_CONTRACT,
  CA_CONTRACT as AELF_CA_CONTRACT,
} from './platform/AELF';
import {
  TOKEN_CONTRACT as AELF_TEST_TOKEN_CONTRACT,
  ETRANSFER_CONTRACT as AELF_TEST_ETRANSFER_CONTRACT,
  CA_CONTRACT as AELF_TEST_CA_CONTRACT,
} from './platform/AELF_Test';
import {
  TOKEN_CONTRACT as TDVV_TOKEN_CONTRACT,
  ETRANSFER_CONTRACT as TDVV_ETRANSFER_CONTRACT,
  CA_CONTRACT as TDVV_CA_CONTRACT,
} from './platform/tDVV';
import {
  TOKEN_CONTRACT as TDVW_TOKEN_CONTRACT,
  ETRANSFER_CONTRACT as TDVW_ETRANSFER_CONTRACT,
  CA_CONTRACT as TDVW_CA_CONTRACT,
} from './platform/tDVW_Test';

export enum AllSupportedELFChainId {
  AELF = 'AELF',
  tDVV = 'tDVV',
  tDVW = 'tDVW',
}

export enum ContractType {
  CA = 'CA_CONTRACT',
  TOKEN = 'TOKEN_CONTRACT',
  ETRANSFER = 'ETRANSFER_CONTRACT',
}

export const ADDRESS_MAP = {
  [AllSupportedELFChainId.AELF]: {
    [ContractType.CA]: NETWORK_TYPE === 'MAIN' ? AELF_CA_CONTRACT : AELF_TEST_CA_CONTRACT,
    [ContractType.TOKEN]: NETWORK_TYPE === 'MAIN' ? AELF_TOKEN_CONTRACT : AELF_TEST_TOKEN_CONTRACT,
    [ContractType.ETRANSFER]:
      NETWORK_TYPE === 'MAIN' ? AELF_ETRANSFER_CONTRACT : AELF_TEST_ETRANSFER_CONTRACT,
  },
  [AllSupportedELFChainId.tDVV]: {
    [ContractType.CA]: TDVV_CA_CONTRACT,
    [ContractType.TOKEN]: TDVV_TOKEN_CONTRACT,
    [ContractType.ETRANSFER]: TDVV_ETRANSFER_CONTRACT,
  },
  [AllSupportedELFChainId.tDVW]: {
    [ContractType.CA]: TDVW_CA_CONTRACT,
    [ContractType.TOKEN]: TDVW_TOKEN_CONTRACT,
    [ContractType.ETRANSFER]: TDVW_ETRANSFER_CONTRACT,
  },
};
